### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by naorzr** [mylesj/deep-entries#24]
First off, thanks for doing this! 
It's a very niche need, but exactly what I was looking for,

Are you still actively maintaining this repo? do. u accept prs (mainly for a better typescript definitions)
or should I go about and fork it?

**Comment by mylesj** [comment]
Thanks for your interest. 

Yes I still maintain this though the scope of the project is intentionally narrow and other than maybe adding a breadth first search I view it as reasonably complete. I didn't intend to introduce the TypeScript compiler itself but am open to discussing changes to the [declaration file](https://github.com/mylesj/deep-entries/blob/master/types.d.ts) if there are improvements that you think are worth considering?

I had previously dismissed some alternative options to what is currently published, namely:
  - any kind of method overloading to cover the variable nature of the so called `DeepEntries` - which I felt degraded the intellisense in my IDE
  - recursive types which seem to choke on larger inputs 

I'd be most interested in improvements for intellisense, readability or basic type-inference rather than stricter type checking as for my use-case and what I envision the util mainly being used for is traversing arbitrary JSON input where by nature, the shape of the data is unchecked anyway. 

I am keen to keep things simple, if other use-cases could benefit from more complex typings then it might also be worth looking at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) as another option - I believe a second set of types there could override what is defined in this repository?
